export const imgDict = {
    "mercury": '/Images/Mercury.jpg',
    "venus": '/Images/Venus.jpg',
    "earth": '/Images/Earth.jpg',
    "mars": '/Images/Mars.jpg',
    "jupiter": '/Images/Jupiter.jpg',
    "saturn": '/Images/Saturn.jpg',
    "uranus": '/Images/Uranus.jpg',
    "neptune": '/Images/Neptune.jpg',
    "moon": '/Images/Moon.jpg',
    "phobos": '/Images/Phobos.jpg',
    "deimos": '/Images/Deimos.jpg',
    "ganymede": '/Images/Ganymede.jpg',
    "europa":'/Images/Europa.jpg',
    "io":'/Images/Io.jpg',
    "callisto": '/Images/Callisto.jpg',
    "titan": '/Images/Titan.jpg',
    "enceladus": '/Images/Enceladus.jpg',
    "mimas": '/Images/Mimas.jpg',
    "dione": '/Images/Dione.jpg',
};